### PR TITLE
atomic: Print help by default if no arguments supplied

### PR DESCRIPTION
**Pull request by cgwalters**
Thanks to http://stackoverflow.com/questions/4042452/display-help-message-with-python-argparse-when-script-is-called-without-any-argu

### CODE REVIEW

**Comment by rhatdan** [comment]
I am not crazy about this though, I thought it was less complete.  The problem I have with this type of interaction is as the commands become more complex the data scrolls off the screen.

**Comment by rhatdan** [comment]
I prefer this type 

 ls --foobar
ls: unrecognized option '--foobar'
Try 'ls --help' for more information.
[Exit 2]

**Comment by cgwalters** [comment]
Right now it's just 18 lines, enough to fit even within the default 24 terminal lines.  Running `docker` is 89, which is getting to be a lot.  `systemctl` shows you the units by default, which I never use.

If it gets longer, we can customize it to be shorter?

**Comment by rhatdan** [comment]
But I still loose the error in the noise.

**Comment by rhatdan** [comment]
How about we put the error at the bottom rather then the top

**Comment by rhatdan** [comment]
./atomic
usage: atomic [-h] {defaults,host,info,install,run,uninstall,update} ...

Atomic Management Tool

positional arguments:
  {defaults,host,info,install,run,uninstall,update}
                        Commands
    defaults            list default commands with which Atomic will
                        RUN/INSTALL/UNINSTALL containers
    host                execute Atomic host commands
    info                dispaly label information about an image
    install             execute container image install method
    run                 execute container image run method.
    uninstall           execute container image uninstall method
    update              pull latest container image from repository

optional arguments:
  -h, --help            show this help message and exit

error: too few arguments

**Comment by cgwalters** [comment]
Error at bottom is :+1: from me

**Pull request merged**
